#!/bin/bash

if [ -z $1 ]; then
    echo "usage: "
    echo "  translate <file> [config]"
    echo "where: "
    echo "  <file>     is a mm source without .mm extension"
    echo "  [config]   is a config of test launching"
    echo
    exit 0
fi

if [ -z $2 ]; then 
	config=./config
else
	config=$2
fi

source ${config}

binpath=`pwd`/$binpath

cd $mathpath

file=$1

if [ -d tmp ]; then
    rm -fr tmp
fi

mkdir tmp

if [ ! -f ${file}.mm ]; then
    echo "source file ${file}.mm desn't exist"
    echo "current dir: " `pwd`
    exit 1
fi

cp ${file}.mm ./tmp/${file}.mm
cd tmp

echo "----------------------"
echo "MM <-> SMM TRANSLATION"
echo "----------------------"

echo "mm -> smm"
check "${binpath}/mdl 
    \"mm opts verbose\" 
    \"smm opts verbose\"  
    \"mm read ${file}.mm\"  
    \"mm transl ${file}.mm ${file}.smm\" 
    \"smm write ${file}.smm\"
    \"smm systems\"
    \"mm systems\"
    \"rus systems\""
echo -e 'done\n\n'


echo "smm -> mm"
check "${binpath}/mdl
    \"mm opts verbose\" 
    \"smm opts verbose\"  
    \"smm read ${file}.smm \"  
    \"smm transl mm ${file}.smm ${file}-0.mm\" 
    \"mm write ${file}-0.mm\"
    \"smm systems\"
    \"mm systems\"
    \"rus systems\""
echo -e 'done\n\n'

echo "verify mm"
${binpath}/metamath "read ${file}-0.mm" 'verify proof *' exit
echo -e 'done\n'


echo
echo

echo "----------------------"
echo "MM <-> RUS TRANSLATION"
echo "----------------------"

echo "smm -> rus"
check "${binpath}/mdl
	\"smm opts verbose\" 
    \"rus opts verbose\"  
    \"smm read ${file}.smm \"  
    \"smm transl rus ${file}.smm ${file}.rus\" 
    \"rus write ${file}.rus\"
    \"smm systems\"
    \"mm systems\"
    \"rus systems\""
echo -e 'done\n\n'


echo "rus -> smm"
check "${binpath}/mdl 
	\"rus opts verbose\" 
    \"smm opts verbose\"  
    \"rus read ${file}.rus \" 
    \"rus parse \" 
    \"rus transl ${file}.rus ${file}-1.smm\" 
    \"smm write ${file}-1.smm\"
    \"smm systems\"
    \"mm systems\"
    \"rus systems\""
echo -e 'done\n\n'


echo "verify smm"
check "${binpath}/mdl
    \"smm opts verbose\"  
    \"smm read ${file}-1.smm \" 
    \"smm verify ${file}-1.smm\"
    \"smm systems\"
    \"mm systems\"
    \"rus systems\""
echo -e 'done\n'


echo "smm -> mm"
check "${binpath}/mdl
	\"mm opts verbose\" 
    \"smm opts verbose\"  
    \"smm read ${file}-1.smm \"  
    \"smm transl mm ${file}-1.smm ${file}-1.mm\" 
    \"mm write ${file}-1.mm\""
echo -e 'done\n\n'


echo "mm -> smm"
check "${binpath}/mdl
	\"mm opts verbose\" 
    \"smm opts verbose\"  
    \"mm read ${file}-1.mm \"  
    \"mm transl ${file}-1.mm $file-2.smm\" 
    \"smm write $file-2.smm\""
echo -e 'done\n'


echo "verify smm"
check "${binpath}/mdl
	\"smm opts verbose\"  
    \"smm read ${file}-2.smm \" 
    \"smm verify ${file}-2.smm\"
    \"smm systems\"
    \"mm systems\"
    \"rus systems\""
echo -e 'done\n'


echo "verify mm"
${binpath}/metamath "read ${file}-1.mm" 'verify proof *' exit
echo -e 'done\n'

echo -e 'translation tests passed =)\n'

