#!/bin/bash

if [ -z $1 ]; then
    echo "usage: "
    echo "  translate <file> [memcheck]"
    echo "where: "
    echo "  <file>     is a mm source without .mm extension"
    echo "  [memcheck] is an option for memory leaks tests (slows down the script)"
    echo
    exit 0
fi

if [ -z $2 ]; then 
	config=./config
else
	config=$2
fi

source ${config}

binpath=`pwd`/$binpath

cd $mathpath

file=$1

if [ -d tmp ]; then
    rm -fr tmp
fi

mkdir tmp

if [ ! -f ${file}.mm ]; then
    echo "source file ${file}.mm desn't exist"
    echo "current dir: " `pwd`
    exit 1
fi

cp ${file}.mm ./tmp/${file}.mm
cd tmp

VALGRIND="valgrind --tool=memcheck --leak-check=full"

function check() {
    echo $1
    if [ "$memcheck" == "yes" ]; then
	$VALGRIND $1
    else
	$1
    fi
}

echo "----------------------"
echo "MM <-> SMM TRANSLATION"
echo "----------------------"

echo "mm -> smm"
check "${binpath}/mm -t -v -i ${file}.mm  -o $file.smm"
echo -e 'done\n\n'

if [ $? != 0 ]; then 
    echo "TEST FAILED."; exit
fi;


echo "smm -> mm"
check "${binpath}/smm -v -i ${file}.smm -o ${file}-0.mm"
echo -e 'done\n\n'

if [ $? != 0 ]; then
    echo "TEST FAILED."; exit
fi;

echo "verify mm"
${binpath}/metamath "read ${file}-0.mm" 'verify proof *' exit
echo -e 'done\n'

if [ $? != 0 ]; then 
    echo "TEST FAILED."; exit
fi;


echo
echo

echo "----------------------"
echo "MM <-> RUS TRANSLATION"
echo "----------------------"

echo "smm -> rus"
check "${binpath}/smm -v -i ${file}.smm -o ${file}.rus"
echo -e 'done\n\n'

if [ $? != 0 ]; then 
    echo "TEST FAILED."; exit
fi;


echo "rus -> smm"
check "${binpath}/rus -t --info -v -i ${file}.rus -o ${file}-1.smm"
echo -e 'done\n\n'

if [ $? != 0 ]; then 
    echo "TEST FAILED."; exit
fi;


echo "verify smm"
check "${binpath}/smm -v -i ${file}-1.smm"
echo -e 'done\n'

if [ $? != 0 ]; then 
    echo "TEST FAILED."; exit
fi;


echo "smm -> mm"
check "${binpath}/smm -v -i ${file}-1.smm -o ${file}-1.mm"
echo -e 'done\n\n'

if [ $? != 0 ]; then 
    echo "TEST FAILED."; exit
fi;


echo "mm -> smm"
check "${binpath}/mm -t -v -i ${file}-1.mm -o ${file}-3.smm"
echo -e 'done\n'

if [ $? != 0 ]; then 
    echo "TEST FAILED."; exit
fi;


echo "verify smm"
check "${binpath}/smm -v -i ${file}-3.smm"
echo -e 'done\n'

if [ $? != 0 ]; then 
    echo "TEST FAILED."; exit
fi;


echo "verify mm"
${binpath}/metamath "read ${file}-1.mm" 'verify proof *' exit
echo -e 'done\n'

if [ $? != 0 ]; then 
    echo "TEST FAILED."; exit
fi;


echo -e 'translation tests passed =)\n'

