#!/bin/bash 

function run() {
    eval $1
	if [ $? != 0 ]; then 
		echo -e '\n\nTEST FAILED.'; exit 1
	fi;
}

#VALGRIND="valgrind --tool=exp-sgcheck"
VALGRIND="valgrind --tool=memcheck "

function check() {
	if [ "$output_command" == 'yes' ]; then
		echo "COMMAND: " $1
	fi
    if [ "$memcheck" == "yes" ]; then
		run "$VALGRIND $@"
    else
		run "$@"
    fi
}
