#!/bin/bash

if [ -z $1 ]; then
    echo "usage: "
    echo "  test_deep_altogether <file> [config]"
    echo "where: "
    echo "  <file>     is a mm source without .mm extension"
    echo "  [config]   is a config of test launching"
    echo
    exit 0
fi

if [ -z $2 ]; then 
	config=./config
else
	config=$2
fi

source ${config}

binpath=`pwd`/$binpath

cd $mathpath

file=$1

if [ ! -f ${file}.mm ]; then
    echo "source file ${file}.mm desn't exist"
	echo "current dir: " `pwd`
    exit 1
fi

if [ -d tmp-deep ]; then
    rm -fr tmp-deep
fi

mkdir tmp-deep

cp ${file}.mm ./tmp-deep/${file}.mm
cd tmp-deep


echo "------------------------------"
echo "Starting a daemon...."
echo "------------------------------"

(check "${binpath}/mdl -d -v 1>&1 2>&2")&

sleep 5

echo "------------------------------"
echo "MM <-> SMM <-> RUS TRANSLATION"
echo "------------------------------"


echo "cut: mm -> mm"
run "${binpath}/mdl -c -v
    \"mm  opts verbose\" 
    \"smm opts verbose\" 
    \"rus opts verbose\" 
    
    \"mm  curr proj=A\" 
    \"smm curr proj=A\" 
    \"rus curr proj=A\"
    \"mm  opts verbose\" 
    
    \"mm cut in=${file}.mm out=${file}.smm out-root=mm\"
    
    \"mm  opts verbose root=mm\" 
    \"smm opts verbose root=smm\" 
    \"rus opts verbose root=rus\" 
    
    \"mm read in=${file}.mm\"
    \"mm transl in=${file}.mm out=${file}.smm\" 
    \"smm write in=${file}.smm deep=true\"

    \"smm curr proj=B\"
    \"smm opts verbose root=smm\" 
    \"mm  curr proj=C\"
    \"mm  opts verbose root=mm-0\" 
    
    \"smm read in=${file}.smm\"
    \"smm transl lang=mm in=${file}.smm out=${file}.mm\" 
    \"mm write in=${file}.mm deep=true\"
    \"mm merge in=${file}.mm out=${file}-0.mm out-root=\"

    \"smm transl lang=rus in=${file}.mm out=${file}.rus\" 
    \"rus write in=${file}.rus deep=true\"
    \"rus curr proj=B\"
    \"rus opts verbose root=rus\" 
    \"rus read in=${file}.rus\"
    \"rus parse \"
    \"smm curr proj=C\"
    \"smm opts verbose root=smm-1\"
    \"rus transl in=${file}.rus out=${file}.smm\" 
    \"smm write in=${file}.smm deep=true\"
    
    \"smm curr proj=D\"
    \"smm opts verbose root=smm-1\" 
    
    \"smm read in=${file}.smm\"
    \"smm verify in=${file}.smm\"
    
    \"mm  curr proj=E\" 
    \"mm  opts verbose root=mm-1\" 
    \"smm transl lang=mm in=${file}.smm out=${file}.mm\" 
    \"mm write in=${file}.mm deep=true\"
    
    \"smm curr proj=E\"
    \"smm opts verbose root=smm-2\"
    \"mm read in=${file}.mm\"
    \"mm transl in=${file}.mm out=${file}.smm\" 
    \"smm write in=${file}.smm deep=true\"
    
    \"smm curr proj=А\"
    \"smm opts verbose root=smm-2\" 
    \"smm read in=${file}.smm\"
    \"smm verify in=${file}.smm\"
    \"mm merge in=${file}.mm out=${file}-1.mm out-root=\"
    
    \"daemon exit\" 
    exit
    "
echo -e 'done\n'

#    \"mm destroy\"
#    \"smm destroy\"
#    \"rus destroy\"

echo "verify mm"
${binpath}/metamath "read ${file}-0.mm" 'verify proof *' exit
echo -e 'done\n'

echo "verify mm"
${binpath}/metamath "read ${file}-1.mm" 'verify proof *' exit
echo -e 'done\n'


echo -e 'translation tests passed =)\n'

