#!/bin/bash

if [ -z $1 ]; then
    echo "usage: "
    echo "  test2_deep_one_by_one <file> [config]"
    echo "where: "
    echo "  <file>     is a mm source without .mm extension"
    echo "  [config]   is a config of test launching"
    echo
    exit 0
fi

if [ -z $2 ]; then 
	config=./config
else
	config=$2
fi

source ${config}

binpath=`pwd`/$binpath

cd $mathpath

file=$1

if [ ! -f ${file}.mm ]; then
    echo "source file ${file}.mm desn't exist"
	echo "current dir: " `pwd`
    exit 1
fi

if [ -d tmp-deep ]; then
    rm -fr tmp-deep
fi

mkdir tmp-deep

cp ${file}.mm ./tmp-deep/${file}.mm
cd tmp-deep

echo "------------------------------"
echo "Starting a daemon...."
echo "------------------------------"

(check "${binpath}/mdl -d 1>&1 2>&2")&
echo -e 'done\n\n'

echo "-----------------------------------"
echo " MM -> RUS -> MM translation tests "
echo "-----------------------------------"

echo "cut: mm (plain) -> mm (deep)"
check "${binpath}/mdl -c
    \"mm cut in=${file}.mm out=${file}.smm out-root=mm\"
    
    \"rus curr proj=A\"
    \"rus opts verbose root=rus\"
	\"mm curr proj=A\" 
	\"mm opts verbose root=mm\"
    \"mm read in=${file}.mm\"
    \"mm parse \"
    \"mm verify \"
    \"mm transl in=${file}.mm out=${file}.rus\"
    \"rus parse_expr \"
    \"rus min_imports \"
    \"rus write in=${file}.rus deep=true\"
    
    \"rus curr proj=B\"
    \"rus opts verbose root=rus\"
	\"mm curr proj=B\" 
	\"mm opts verbose root=mm-1\"
    \"rus read in=${file}.rus\"
    \"rus parse_src \"
    \"rus parse_expr \"
    \"rus verify \"
    \"rus transl in=${file}.rus out=${file}.mm\" 
    \"mm write in=${file}.mm deep=true\"
    
    \"mm curr proj=C\" 
	\"mm opts verbose root=mm-1\" 
    \"mm read in=${file}.mm\"
    \"mm parse \"
    \"mm verify \"
    \"mm merge in=${file}.mm out=${file}-1.mm out-root=\"
    \"daemon exit\" 
    exit"
echo -e 'done\n\n'


echo "----------------------"
echo "   Metamath VERIFY    "
echo "----------------------"

echo "verify mm-1 (plain) with metamath"
${binpath}/metamath "read ${file}-1.mm" 'verify proof *' 'exit'
echo -e 'done\n'


echo -e 'translation tests passed =)\n'

