#!/bin/bash

if [ -z $1 ]; then
    echo "usage: "
    echo "  test_shallow_one_by_one <file> [config]"
    echo "where: "
    echo "  <file>     is a mm source without .mm extension"
    echo "  [config]   is a config of test launching"
    echo
    exit 0
fi

if [ -z $2 ]; then 
	config=./config
else
	config=$2
fi

source ${config}

binpath=`pwd`/$binpath

cd $mathpath

file=$1

if [ -d tmp ]; then
    rm -fr tmp
fi

mkdir tmp

if [ ! -f ${file}.mm ]; then
    echo "source file ${file}.mm desn't exist"
    echo "current dir: " `pwd`
    exit 1
fi

cp ${file}.mm ./tmp/${file}.mm
cd tmp

echo "----------------------"
echo "MM <-> SMM TRANSLATION"
echo "----------------------"

echo "mm -> smm"
check "${binpath}/mdl 
    \"mm  opts verbose\" 
    \"smm opts verbose\"     
    \"mm  read in=${file}.mm\"  
    \"mm  parse \"
    \"mm  transl in=${file}.mm out=${file}.smm\" 
    \"smm write in=${file}.smm\"
    exit"
echo -e 'done\n\n'


echo "smm -> mm"
check "${binpath}/mdl 
    \"mm  opts verbose\" 
    \"smm opts verbose\"     
    \"smm read in=${file}.smm\" 
    \"smm parse \"
    \"smm transl in=${file}.smm out=${file}-0.mm\" 
    \"mm  write in=${file}-0.mm\"
    exit"
echo -e 'done\n\n'

echo "verify mm"
${binpath}/metamath "read ${file}-0.mm" 'verify proof *' exit
echo -e 'done\n'


echo
echo

echo "----------------------"
echo "MM <-> RUS TRANSLATION"
echo "----------------------"

echo "smm -> rus"
check "${binpath}/mdl 
    \"rus opts verbose\" 
    \"smm opts verbose\"     
    \"smm read in=${file}.smm\" 
    \"smm parse \"
    \"smm transl in=${file}.smm out=${file}.rus\" 
    \"rus write in=${file}.rus\"
    exit"
echo -e 'done\n\n'


echo "rus -> smm"
check "${binpath}/mdl 
    \"rus opts verbose\" 
    \"smm opts verbose\"     
    \"rus read in=${file}.rus\" 
    \"rus parse_src \"
    \"rus parse_expr \"
    \"rus verify \"
    \"rus transl in=${file}.rus out=${file}-1.smm\" 
    \"smm write in=${file}-1.smm deep=true\"
    exit"
echo -e 'done\n\n'


echo "verify smm"
check "${binpath}/mdl 
    \"smm opts verbose\"     
    \"smm read in=${file}-1.smm\" 
    \"smm parse \"
    \"smm verify in=${file}-1.smm\"
    exit"
echo -e 'done\n'


echo "smm -> mm"
check "${binpath}/mdl 
    \"mm  opts verbose\" 
    \"smm opts verbose\"     
    \"smm read in=${file}-1.smm\"
    \"smm parse \"  
    \"smm transl in=${file}-1.smm out=${file}-1.mm\" 
    \"mm  write in=${file}-1.mm deep=true\"
    exit"
echo -e 'done\n\n'


echo "mm -> smm"
check "${binpath}/mdl 
    \"mm  opts verbose\" 
    \"smm opts verbose\"     
    \"mm  read in=${file}-1.mm\"  
    \"mm  parse \"
    \"mm  transl in=${file}-1.mm out=${file}-2.smm\" 
    \"smm write in=${file}-2.smm deep=true\"
    exit"
echo -e 'done\n'


echo "verify smm"
check "${binpath}/mdl 
    \"smm opts verbose\" 
    \"smm read in=${file}-2.smm\"  
    \"smm parse \"
    \"smm verify in=${file}-2.smm\"
    exit"
echo -e 'done\n'


echo "verify mm"
${binpath}/metamath "read ${file}-1.mm" 'verify proof *' exit
echo -e 'done\n'

echo -e 'translation tests passed =)\n'

