#!/bin/bash

if [ -z $1 ]; then
    echo "usage: "
    echo "  test2_deep_one_by_one <file> [config]"
    echo "where: "
    echo "  <file>     is a mm source without .mm extension"
    echo "  [config]   is a config of test launching"
    echo
    exit 0
fi

if [ -z $2 ]; then 
	config=./config
else
	config=$2
fi

source ${config}

binpath=`pwd`/$binpath

cd $mathpath

file=$1

if [ ! -f ${file}.mm ]; then
    echo "source file ${file}.mm desn't exist"
	echo "current dir: " `pwd`
    exit 1
fi

if [ -d tmp-deep ]; then
    rm -fr tmp-deep
fi

mkdir tmp-deep

cp ${file}.mm ./tmp-deep/${file}.mm
cd tmp-deep

echo "----------------------"
echo "      MM CUT "
echo "----------------------"

echo "cut: mm (plain) -> mm (deep)"
check "${binpath}/mdl --verb
    \"mm opts verbose\"
    \"mm cut in=${file}.mm out=${file}.smm out-root=mm\"
    exit"

echo -e 'done\n\n'

echo "----------------------"
echo "MM -> RUS TRANSLATION"
echo "----------------------"

echo "mm -> rus"
check "${binpath}/mdl --verb
    \"mm opts verbose root=mm\" 
    \"rus opts verbose root=rus\" 
    \"mm read in=${file}.mm\"
    \"mm parse \"
    \"mm verify \"
    \"mm transl in=${file}.mm out=${file}.rus\"
    \"rus parse_expr \"
    \"rus min_imports \"
    \"rus write in=${file}.rus deep=true\"
    \"rus verify \"
    \"rus write in=${file}.rus deep=true\"
    exit"
echo -e 'done\n\n'


#\"rus refactor job=shortcut_proofs \"

# \"rus refactor job=reduce_duplicate_steps \"
#\"rus refactor job=reduce_unused_hyps \"
#\"rus refactor job=reduce_unused_steps \"
# \"rus refactor job=shortcut_proofs \"
#\"rus refactor job=reduce_unused_steps \"
#\"rus refactor job=reduce_proofs \"

#\"mm2 minimize in=${file}.mm\"

echo "----------------------"
echo "RUS -> MM TRANSLATION"
echo "----------------------"

echo "rus -> mm"
check "${binpath}/mdl --verb
    \"mm opts verbose root=mm-1\" 
    \"rus opts verbose root=rus\" 
    \"rus read in=${file}.rus\"
    \"rus parse_src \"
    \"rus parse_expr \"
    \"rus verify \"
    \"rus transl in=${file}.rus out=${file}.mm\" 
    \"mm write in=${file}.mm deep=true\"
    \"mm merge in=${file}.mm out=${file}-1.mm out-root=\"
    exit"
echo -e 'done\n\n'

echo "----------------------"
echo "      MM VERIFY       "
echo "----------------------"

echo "verify mm-1 with mm2"
check "${binpath}/mdl --verb
    \"mm opts verbose root=mm-1\" 
    \"mm read in=${file}.mm\"
    \"mm parse \"
    \"mm verify \"
    exit"
echo -e 'done\n\n'

echo "----------------------"
echo "   Metamath VERIFY    "
echo "----------------------"

echo "verify mm-1 (plain) with metamath"
${binpath}/metamath "read ${file}-1.mm" 'verify proof *' 'exit'
echo -e 'done\n'


echo -e 'translation tests passed =)\n'

