#!/bin/bash

if [ -z $1 ]; then
    echo "usage: "
    echo "  translate_shallow <file> [config]"
    echo "where: "
    echo "  <file>     is a mm source without .mm extension"
    echo "  [config]   is a config of test launching"
    echo
    exit 0
fi

if [ -z $2 ]; then 
	config=./config
else
	config=$2
fi

source ${config}

binpath=`pwd`/$binpath

cd $mathpath

file=$1

if [ -d tmp ]; then
    rm -fr tmp
fi

mkdir tmp

if [ ! -f ${file}.mm ]; then
    echo "source file ${file}.mm desn't exist"
    echo "current dir: " `pwd`
    exit 1
fi

cp ${file}.mm ./tmp/${file}.mm
cd tmp

echo "----------------------"
echo "MM -> SMM TRANSLATION"
echo "----------------------"

echo "mm -> smm"
check "${binpath}/mdl 
    \"mm  opts verbose\" 
    \"smm opts verbose\"     
    \"mm  read in=${file}.mm\"  
    \"mm  transl in=${file}.mm out=${file}.smm\" 
    \"smm write in=${file}.smm\"
    exit"
echo -e 'done\n\n'

echo
echo

echo "----------------------"
echo "MM -> RUS TRANSLATION"
echo "----------------------"

echo "smm -> rus"
check "${binpath}/mdl 
    \"rus opts verbose\" 
    \"smm opts verbose\"     
    \"smm read in=${file}.smm\"  
    \"smm transl lang=rus in=${file}.smm out=${file}.rus\" 
    \"rus write in=${file}.rus\"
    exit"
echo -e 'done\n\n'

echo -e 'translation is done =)\n'

