#!/bin/bash

if [ -z $1 ]; then
    echo "usage: "
    echo "  translate_deep <file> [config]"
    echo "where: "
    echo "  <file>     is a mm source without .mm extension"
    echo "  [config]   is a config of test launching"
    echo
    exit 0
fi

if [ -z $2 ]; then 
	config=./config
else
	config=$2
fi

source ${config}

binpath=`pwd`/$binpath

cd $mathpath

file=$1

if [ ! -f ${file}.mm ]; then
    echo "source file ${file}.mm desn't exist"
	echo "current dir: " `pwd`
    exit 1
fi

if [ -d tmp-deep ]; then
    rm -fr tmp-deep
fi

mkdir tmp-deep

cp ${file}.mm ./tmp-deep/${file}.mm
cd tmp-deep

echo "----------------------"
echo "   MM -> MM CUTTING"
echo "----------------------"

echo "cut: mm -> mm"
check "${binpath}/mdl 
    \"mm opts verbose\"
    \"mm cut in=${file}.mm out=${file}.smm out-root=mm\"
    exit"

echo -e 'done\n\n'

echo "-----------------------"
echo " MM -> SMM TRANSLATION "
echo "-----------------------"


echo "mm -> smm"
check "${binpath}/mdl 
    \"mm  opts verbose root=mm\" 
    \"smm opts verbose root=smm\" 
    \"mm  read in=${file}.mm\"
    \"mm parse \"
    \"mm  transl in=${file}.mm out=${file}.smm\" 
    \"smm write in=${file}.smm deep=true\"
    exit"
echo -e 'done\n\n'

echo "------------------------"
echo " SMM -> RUS TRANSLATION "
echo "------------------------"

echo "smm -> rus"
check "${binpath}/mdl 
    \"smm opts verbose root=smm\" 
    \"rus opts verbose root=rus\" 
    \"smm read in=${file}.smm\"
    \"smm parse \"
    \"smm transl in=${file}.mm out=${file}.rus\"
    \"rus write in=${file}.rus deep=true\"
    exit"
echo -e 'done\n\n'

echo -e 'translation is done =)\n'

