#include "com/actions.cpp"
#include "com/log.cpp"
#include "com/common.cpp"
#include "com/memusage.cpp"
#include "com/timer.cpp"
#include "com/xml.cpp"

#include "daem.cpp"

#include "rus/sys.cpp"
#include "smm/sys.cpp"
#include "mm/mm_sys.cpp"

#include "mm/mm_ast.cpp"
#include "mm/mm_cut.cpp"
#include "mm/mm_merge.cpp"
#include "mm/mm_parser.cpp"
#include "mm/mm_show.cpp"
#include "mm/mm_translate.cpp"

#include "rus/expr/parse.cpp"
#include "rus/expr/unify.cpp"
#include "rus/parser/parse.cpp"
#include "rus/ast.cpp"
#include "rus/expr.cpp"
#include "rus/memvol.cpp"
//#include "parser.cpp"
#include "rus/show.cpp"
#include "rus/translate.cpp"
#include "rus/verify.cpp"
#include "rus/xml.cpp"

#include "smm/ast.cpp"
#include "smm/parser.cpp"
#include "smm/show.cpp"
#include "smm/translate_mm.cpp"
#include "smm/translate_rus.cpp"
#include "smm/tree.cpp"
#include "smm/verify.cpp"
