#include "com/common.cpp"
#include "com/memusage.cpp"
#include "com/timer.cpp"

#include "daem/daemon.cpp"

#include "mm/sys.cpp"
#include "rus/sys.cpp"
#include "smm/sys.cpp"

#include "mm/ast.cpp"
#include "mm/cut.cpp"
#include "mm/merge.cpp"
#include "mm/parser.cpp"
#include "mm/show.cpp"
#include "mm/translate.cpp"

#include "rus/expr/parse.cpp"
#include "rus/expr/unify.cpp"
#include "rus/parser/parse.cpp"
#include "rus/ast.cpp"
#include "rus/expr.cpp"
#include "rus/memvol.cpp"
//#include "parser.cpp"
#include "rus/show.cpp"
#include "rus/translate.cpp"
#include "rus/verify.cpp"

#include "smm/ast.cpp"
#include "smm/parser.cpp"
#include "smm/show.cpp"
#include "smm/translate_mm.cpp"
#include "smm/translate_rus.cpp"
#include "smm/tree.cpp"
#include "smm/verify.cpp"
