#include "com/actions.cpp"
#include "com/log.cpp"
#include "com/common.cpp"
#include "com/memusage.cpp"
#include "com/timer.cpp"
#include "com/xml.cpp"

#include "daem.cpp"

#include "mm/mm_sys.cpp"
#include "smm/smm_sys.cpp"
#include "rus/rus_sys.cpp"

#include "mm/mm_ast.cpp"
#include "mm/mm_cut.cpp"
#include "mm/mm_merge.cpp"
#include "mm/mm_parser.cpp"
#include "mm/mm_show.cpp"
#include "mm/mm_translate.cpp"

#include "rus/expr/rus_expr_parse.cpp"
#include "rus/expr/rus_expr_unify.cpp"
#include "rus/parser/rus_parser.cpp"
#include "rus/rus_ast.cpp"
#include "rus/rus_expr.cpp"
#include "rus/rus_memvol.cpp"
#include "rus/rus_show.cpp"
#include "rus/rus_translate.cpp"
#include "rus/rus_verify.cpp"
#include "rus/rus_xml.cpp"

//#include "parser.cpp"
#include "smm/smm_ast.cpp"
#include "smm/smm_parser.cpp"
#include "smm/smm_show.cpp"
#include "smm/smm_translate_mm.cpp"
#include "smm/smm_translate_rus.cpp"
#include "smm/smm_tree.cpp"
#include "smm/smm_verify.cpp"
